apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "vitess-operator.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: vitess-operator
      {{- include "vitess-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: vitess-operator
        {{- include "vitess-operator.labels" . | nindent 8 }}
    spec:
      priorityClassName: {{ .Values.priorityClassName }}
      serviceAccountName: {{ include "vitess-operator.serviceAccountName" . }}
      containers:
      - name: vitess-operator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
        {{- with .Values.command }}
        command:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.args }}
        args: 
          {{- toYaml . | nindent 12 }}
        {{- end }}
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PS_OPERATOR_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PS_OPERATOR_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "vitess-operator"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
