kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vitess-operator
subjects:
- kind: ServiceAccount
  name: {{ include "vitess-operator.serviceAccountName" . }}
roleRef:
  kind: Role
  name: vitess-operator
  apiGroup: rbac.authorization.k8s.io
